    [theme]
    primaryColor = '#FF4B4B'  # Primary accent for interactive elements
    backgroundColor = '#F0F2F6' # Background color for the main content area
    secondaryBackgroundColor = '#FFFFFF' # Background color for sidebar and most interactive widgets
    textColor = '#262730' # Color used for almost all text
    font = 'sans serif' # Font family for all text (sans serif | serif | monospace
